mutation register($name: String!, $email: String!, $password: String!) {
  register(name: $name, email: $email, password: $password) {
    user {
      id
      name
    }
    token
    user {
      name
      email
      houses {
        id
        name
        users
        items {
          id
          name
          stores {
            id
            name
          }
        }
      }
    }
  }
}
